# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'doctor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 600))
        MainWindow.setSizeIncrement(QtCore.QSize(1000, 800))
        MainWindow.setBaseSize(QtCore.QSize(1000, 600))
        MainWindow.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"font: 75 12pt \"Fixedsys\";\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 230, 951, 341))
        self.tableWidget.setStyleSheet("background-color: rgb(218, 218, 218);\n"
"border-radius: 5px;")
        self.tableWidget.setDragEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.Dell = QtWidgets.QPushButton(self.centralwidget)
        self.Dell.setGeometry(QtCore.QRect(20, 10, 111, 31))
        self.Dell.setStyleSheet("background-color: rgb(255, 207, 64);\n"
"")
        self.Dell.setObjectName("Dell")
        self.Add = QtWidgets.QPushButton(self.centralwidget)
        self.Add.setGeometry(QtCore.QRect(20, 50, 111, 31))
        self.Add.setStyleSheet("background-color: rgb(255, 207, 64);\n"
"")
        self.Add.setObjectName("Add")
        self.Change = QtWidgets.QPushButton(self.centralwidget)
        self.Change.setGeometry(QtCore.QRect(20, 90, 111, 31))
        self.Change.setStyleSheet("background-color: rgb(255, 207, 64);\n"
"")
        self.Change.setObjectName("Change")
        self.Open = QtWidgets.QPushButton(self.centralwidget)
        self.Open.setGeometry(QtCore.QRect(20, 130, 111, 31))
        self.Open.setStyleSheet("background-color: rgb(255, 207, 64);\n"
"")
        self.Open.setObjectName("Open")
        self.Sort = QtWidgets.QPushButton(self.centralwidget)
        self.Sort.setGeometry(QtCore.QRect(20, 170, 111, 31))
        self.Sort.setStyleSheet("background-color: rgb(255, 207, 64);\n"
"")
        self.Sort.setObjectName("Sort")
        self.Back = QtWidgets.QPushButton(self.centralwidget)
        self.Back.setGeometry(QtCore.QRect(900, 0, 101, 20))
        self.Back.setStyleSheet("background-color: rgb(255, 207, 64);\n"
"")
        self.Back.setObjectName("Back")
        self.DellLine = QtWidgets.QLineEdit(self.centralwidget)
        self.DellLine.setGeometry(QtCore.QRect(150, 10, 101, 31))
        self.DellLine.setStyleSheet("background-color: rgb(218, 218, 218);\n"
"border-radius: 5px;")
        self.DellLine.setObjectName("DellLine")
        self.AddLine = QtWidgets.QLineEdit(self.centralwidget)
        self.AddLine.setGeometry(QtCore.QRect(150, 50, 81, 31))
        self.AddLine.setStyleSheet("background-color: rgb(218, 218, 218);\n"
"border-radius: 5px;")
        self.AddLine.setObjectName("AddLine")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_13.setGeometry(QtCore.QRect(150, 170, 101, 31))
        self.lineEdit_13.setStyleSheet("background-color: rgb(218, 218, 218);\n"
"border-radius: 5px;")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.AddLine_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.AddLine_2.setGeometry(QtCore.QRect(250, 50, 81, 31))
        self.AddLine_2.setStyleSheet("background-color: rgb(218, 218, 218);\n"
"border-radius: 5px;")
        self.AddLine_2.setObjectName("AddLine_2")
        self.AddLine_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.AddLine_3.setGeometry(QtCore.QRect(350, 50, 81, 31))
        self.AddLine_3.setStyleSheet("background-color: rgb(218, 218, 218);\n"
"border-radius: 5px;")
        self.AddLine_3.setObjectName("AddLine_3")
        self.AddLine_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.AddLine_4.setGeometry(QtCore.QRect(450, 50, 81, 31))
        self.AddLine_4.setStyleSheet("background-color: rgb(218, 218, 218);\n"
"border-radius: 5px;")
        self.AddLine_4.setObjectName("AddLine_4")
        self.AddLine_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.AddLine_5.setGeometry(QtCore.QRect(550, 50, 81, 31))
        self.AddLine_5.setStyleSheet("background-color: rgb(218, 218, 218);\n"
"border-radius: 5px;")
        self.AddLine_5.setObjectName("AddLine_5")
        self.AddLine_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.AddLine_6.setGeometry(QtCore.QRect(650, 50, 81, 31))
        self.AddLine_6.setStyleSheet("background-color: rgb(218, 218, 218);\n"
"border-radius: 5px;")
        self.AddLine_6.setObjectName("AddLine_6")
        self.AddLine_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.AddLine_8.setGeometry(QtCore.QRect(150, 90, 81, 31))
        self.AddLine_8.setStyleSheet("background-color: rgb(218, 218, 218);\n"
"border-radius: 5px;")
        self.AddLine_8.setObjectName("AddLine_8")
        self.AddLine_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.AddLine_9.setGeometry(QtCore.QRect(250, 90, 81, 31))
        self.AddLine_9.setStyleSheet("background-color: rgb(218, 218, 218);\n"
"border-radius: 5px;")
        self.AddLine_9.setObjectName("AddLine_9")
        self.AddLine_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.AddLine_10.setGeometry(QtCore.QRect(350, 90, 81, 31))
        self.AddLine_10.setStyleSheet("background-color: rgb(218, 218, 218);\n"
"border-radius: 5px;")
        self.AddLine_10.setObjectName("AddLine_10")
        self.AddLine_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.AddLine_11.setGeometry(QtCore.QRect(450, 90, 81, 31))
        self.AddLine_11.setStyleSheet("background-color: rgb(218, 218, 218);\n"
"border-radius: 5px;")
        self.AddLine_11.setObjectName("AddLine_11")
        self.AddLine_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.AddLine_12.setGeometry(QtCore.QRect(550, 90, 81, 31))
        self.AddLine_12.setStyleSheet("background-color: rgb(218, 218, 218);\n"
"border-radius: 5px;")
        self.AddLine_12.setObjectName("AddLine_12")
        self.AddLine_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.AddLine_13.setGeometry(QtCore.QRect(650, 90, 81, 31))
        self.AddLine_13.setStyleSheet("background-color: rgb(218, 218, 218);\n"
"border-radius: 5px;")
        self.AddLine_13.setObjectName("AddLine_13")
        self.AddLine_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.AddLine_14.setGeometry(QtCore.QRect(750, 90, 81, 31))
        self.AddLine_14.setStyleSheet("background-color: rgb(218, 218, 218);\n"
"border-radius: 5px;")
        self.AddLine_14.setObjectName("AddLine_14")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "drivers"))
        self.Dell.setText(_translate("MainWindow", "Удалить"))
        self.Add.setText(_translate("MainWindow", "Добавть"))
        self.Change.setText(_translate("MainWindow", "Изменить"))
        self.Open.setText(_translate("MainWindow", "Открыть"))
        self.Sort.setText(_translate("MainWindow", "Сортировать"))
        self.Back.setText(_translate("MainWindow", "Назад"))
